### PR TITLE
Support launching the token dApp in `service run` command

### LINKED ISSUE #408: Add token dApp to network configuration
Some browsers on some operating systems (difficult to pin down exactly what) will not allow connections from https sites to localhost via http. 

Meaning that connecting a website e.g. https://token.vega.xyz to your local wallet can be difficult. This is why the `--console-proxy` option exists and why there is a line in a network config to define where "Console" lives for that network.

However, Console isn't the only thing that people will want to connect from.

Suggestion: allow the user to specify any url (as well as have a default in the network config.
```bash
machine:~ me$ ./vegawallet service run -n fairground -p https://token.fairground.wtf
```
-----
Bonus: In some cases I may wish to connect to more than one URL. I'm not sure if something like this is a goer?

```bash
machine:~ me$ ./vegawallet service run -n fairground -p https://token.fairground.wtf, https://console.fairground.wtf
```

### PR DESCRIPTION
**Pull request by ValentinTrinque**
Close #408

### CODE REVIEW

**Comment by edd** [comment]
Could you update the comment/title/changelog (as you feel appropriate) to mention the `create` command also coming in here?

**Review by edd — COMMENTED** [review]
Basic review: Looks fine, but there’s enough go in here that I’ll leave approving it to something else. Config changes look good, my only minor niggle is the changes to the command line should be highlighted a bit more in the changelog/title/something, just so that we remember and co-ordinate docs getting updated.

You’re probably already talking to @candida-d about it, but come the next release you might both be on holiday or something

**Comment by ValentinTrinque** [comment]
@edd 

> Could you update the comment/title/changelog (as you feel appropriate) to mention the create command also coming in here?

It's already here:
```
- [418](https://github.com/vegaprotocol/vegawallet/pull/418) - Add the `create` command to create a wallet
```

> my only minor niggle is the changes to the command line should be highlighted a bit more in the changelog/title/something, just so that we remember and co-ordinate docs getting updated.

No sure which version you are looking at, but I added all of this, already. But maybe it's not clear enough.

**Comment by edd** [comment]
My mistake. I read the title of this PR, then had the thought, and forgot to check that the changelog was correct. So: you've done the right thing.

**Review by peterbarrow — APPROVED** [review]

**Pull request merged**
