### PR TITLE
Add MacOS binary siging

### LINKED ISSUE #42: [OSX] Binary release should be signed
It's possible to run the current release (0.4.2) on OSX, but the end user has to fiddle with security settings to allow running unsigned binaries. This isn't the end of the world, but life would be easier if it was signed in such a way that OSX was happy to run it.

# Tasks
- [ ] Add signing process to OSX build

# References
- https://github.com/git-lfs/git-lfs/pull/4143/commits/bfc5304edf2b218fb8abf22aba02b5dc7e842a4a
- https://developer.apple.com/developer-id/
- https://docs.revenera.com/installanywhere2017/Content/helplibrary/OSX-GetCert.htm

### PR DESCRIPTION
**Pull request by ValentinTrinque**
Close #42

### CODE REVIEW

**Review by pscott31 — APPROVED** [review]
All this looks like nice formatting changes but I can't see where it's actually doing any signing :)

**Comment by ValentinTrinque** [comment]
@pscott31 Sorry I should have mark the PR as draft. At that time the signing wasn't done. Now, it's almost done, the the `release-binaries.yml`

**Comment by wwestgarth** [comment]
Given this is a public repo are there any issues with having the signing automated in the github action? I'm thinking what if someone opens a PR with some malicious code with some fiddled change to `releases.yml`, pushes it to master, and then it gets signed. The result will be a compromised version of the vegawallet signed by us.

I wasn't able to navigate my way through the github settings, but would like it confirmed: is there a restriction on this repo that a PR _needs_ an approval from someone _from vega_ before it can be merged?

**Comment by ValentinTrinque** [comment]
@wwestgarth Fair point. I will investigate

**Comment by ValentinTrinque** [comment]
@wwestgarth I updated the CODEOWNERS and added a branch protection on develop and main

**Pull request merged**
